### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by Sbsknight16** [maksimKorzh/opencv-chess-bot#1]
Sir can you help me. I try Play as Black. But bot try to move my pawn go back. Its look like bot try to promote my pawn.
I think bot move to wrong side
Sory for my bad English

**Comment by maksimKorzh** [comment]
I think I got your issue, make sure you're watching the board from the white's perspective even if you're playing black.
Piece coordinates are hard coded, so if you swap the board it would still think that black pieces are above and the white
pieces are below. I know, it's a bit weird but since this software was never intended for the end user but rather a piece
of code to tinker with I considered this like behavior to be ok)

**Comment by Sbsknight16** [comment]
Thanks for your comment sir. I am very grateful for your work

**Comment by maksimKorzh** [comment]
You're welcome!
